-- ============================================================
-- FamTalk — 하울 고급 학습 단어 (SAT / 수학영어 / 과학영어)
-- 현재 Supabase DB에서 내보낸 백업·재현용 시드. 재실행 안전.
-- Supabase SQL Editor 에서 실행.
-- ============================================================

alter table public.words add column if not exists category text not null default 'general';
alter table public.words add column if not exists subcategory text;
create index if not exists words_category_idx on public.words(category);
do $$
begin
  alter table public.words add constraint words_level_term_uniq unique (level, term);
exception when duplicate_table or duplicate_object then null;
end $$;

insert into public.words (level, term, meaning_ko, example_en, example_ko, pos, category, subcategory) values
('E','expression','식','An algebraic expression contains variables, numbers, and operation symbols.','대수식은 변수, 숫자, 연산 기호를 포함합니다.','noun','math_en','algebra'),
('E','term','항','In the expression 3x + 7, ''3x'' and ''7'' are terms.','식 3x + 7에서 ''3x''와 ''7''은 항입니다.','noun','math_en','algebra'),
('E','constant','상수','In the expression 2y - 3, -3 is the constant term.','식 2y - 3에서 -3은 상수항입니다.','noun','math_en','algebra'),
('E','base','밑','In x², the base is x.','x²에서 밑은 x입니다.','noun','math_en','algebra'),
('E','difference','차','The difference between 10 and 4 is 6.','10과 4의 차는 6입니다.','noun','math_en','algebra'),
('E','quotient','몫','The quotient of 20 divided by 5 is 4.','20을 5로 나눈 몫은 4입니다.','noun','math_en','algebra'),
('E','inequality','부등식','An inequality uses symbols like <, >, ≤, or ≥.','부등식은 <, >, ≤, 또는 ≥와 같은 기호를 사용합니다.','noun','math_en','algebra'),
('E','domain','정의역','The domain of a function is the set of all possible inputs.','함수의 정의역은 가능한 모든 입력의 집합입니다.','noun','math_en','algebra'),
('E','range','치역','The range of a function is the set of all possible outputs.','함수의 치역은 가능한 모든 출력의 집합입니다.','noun','math_en','algebra'),
('E','solution','해','The solution to 3x = 9 is x = 3.','3x = 9의 해는 x = 3입니다.','noun','math_en','algebra'),
('E','intercept','절편','The y-intercept is where the line crosses the y-axis.','y절편은 직선이 y축과 교차하는 지점입니다.','noun','math_en','algebra'),
('E','linear','선형의','A linear equation graphs as a straight line.','선형 방정식은 직선으로 그래프가 그려집니다.','adjective','math_en','algebra'),
('E','quadratic','이차의','A quadratic equation has a term with x².','이차 방정식은 x² 항을 가지고 있습니다.','adjective','math_en','algebra'),
('E','cubic','삼차의','A cubic polynomial has a term with x³.','삼차 다항식은 x³ 항을 가지고 있습니다.','adjective','math_en','algebra'),
('E','term by term','항별로','We multiply the polynomials term by term.','우리는 다항식을 항별로 곱합니다.','adverb phras','math_en','algebra'),
('E','solve','풀다','Solve the equation for x.','x에 대해 방정식을 푸세요.','verb','math_en','algebra'),
('E','evaluate','값을 계산하다','Evaluate the expression when x = 3.','x = 3일 때 식의 값을 계산하세요.','verb','math_en','algebra'),
('E','identity','항등식','An identity is an equation that is true for all values of the variable.','항등식은 변수의 모든 값에 대해 참인 방정식입니다.','noun','math_en','algebra'),
('E','set builder notation','집합 건축 표기법','Set builder notation is used to describe sets.','집합 건축 표기법은 집합을 설명하는 데 사용됩니다.','noun phrase','math_en','algebra'),
('E','interval notation','구간 표기법','Interval notation uses brackets and parentheses to represent sets of numbers.','구간 표기법은 숫자 집합을 나타내기 위해 대괄호와 소괄호를 사용합니다.','noun phrase','math_en','algebra'),
('E','limit','극한','The limit of the function f(x) as x approaches 2 is 5.','x가 2에 가까워질 때 함수 f(x)의 극한값은 5입니다.','noun','math_en','calculus'),
('E','rate of change','변화율','The rate of change of distance with respect to time is velocity.','시간에 대한 거리의 변화율은 속도입니다.','noun phrase','math_en','calculus'),
('E','tangent','접선','The tangent line touches the curve at a single point.','접선은 곡선에 한 점에서 접합니다.','noun','math_en','calculus'),
('E','continuous','연속적인','A function is continuous if its graph can be drawn without lifting the pen.','함수는 펜을 떼지 않고 그래프를 그릴 수 있다면 연속입니다.','adjective','math_en','calculus'),
('E','infinity','무한대','The sequence approaches infinity.','그 수열은 무한대로 수렴합니다.','noun','math_en','calculus'),
('E','sequence','수열','An arithmetic sequence has a common difference.','등차수열은 공차가 같습니다.','noun','math_en','calculus'),
('E','series','급수','The sum of an infinite geometric series can be finite.','무한 등비급수의 합은 유한할 수 있습니다.','noun','math_en','calculus'),
('E','asymptote','점근선','The graph approaches the asymptote but never touches it.','그래프는 점근선에 가까워지지만 절대 만나지 않습니다.','noun','math_en','calculus'),
('E','reciprocal','역수','The reciprocal of 2 is 1/2.','2의 역수는 1/2입니다.','noun','math_en','calculus'),
('E','magnitude','크기','The magnitude of the vector is calculated using the Pythagorean theorem.','벡터의 크기는 피타고라스 정리를 사용하여 계산됩니다.','noun','math_en','calculus'),
('E','vector','벡터','A vector has both magnitude and direction.','벡터는 크기와 방향을 모두 가집니다.','noun','math_en','calculus'),
('E','scalar','스칼라','A scalar quantity has only magnitude.','스칼라 양은 크기만 가집니다.','noun','math_en','calculus'),
('E','exponential','지수의','Exponential growth is very rapid.','지수적 성장은 매우 빠릅니다.','adjective','math_en','calculus'),
('E','logarithm','로그','The logarithm of 100 to base 10 is 2.','밑이 10인 100의 로그는 2입니다.','noun','math_en','calculus'),
('E','summation','합계','The summation symbol is sigma (Σ).','합계 기호는 시그마(Σ)입니다.','noun','math_en','calculus'),
('E','average rate of change','평균 변화율','The average rate of change between two points on a curve is the slope of the secant line.','곡선 위의 두 점 사이의 평균 변화율은 할선의 기울기입니다.','noun phrase','math_en','calculus'),
('E','instantaneous rate of change','순간 변화율','The instantaneous rate of change is the derivative of the function.','순간 변화율은 함수의 도함수입니다.','noun phrase','math_en','calculus'),
('E','triangle','삼각형','An equilateral triangle has three equal sides.','정삼각형은 세 변의 길이가 같습니다.','noun','math_en','geometry'),
('E','circle','원','The circumference of a circle is pi times its diameter.','원의 둘레는 파이 곱하기 지름입니다.','noun','math_en','geometry'),
('E','polygon','다각형','A pentagon is a polygon with five sides.','오각형은 변이 다섯 개인 다각형입니다.','noun','math_en','geometry'),
('E','perimeter','둘레','The perimeter of the garden is 50 meters.','정원의 둘레는 50미터입니다.','noun','math_en','geometry'),
('E','radius','반지름','The radius is half the diameter of a circle.','반지름은 원 지름의 절반입니다.','noun','math_en','geometry'),
('E','diameter','지름','The diameter passes through the center of the circle.','지름은 원의 중심을 통과합니다.','noun','math_en','geometry'),
('E','congruent','합동인','These two triangles are congruent.','이 두 삼각형은 합동입니다.','adjective','math_en','geometry'),
('E','similar','닮은','Similar triangles have the same shape but different sizes.','닮은 삼각형은 모양은 같지만 크기는 다릅니다.','adjective','math_en','geometry'),
('E','vertex','꼭짓점','A triangle has three vertices.','삼각형은 세 개의 꼭짓점을 가집니다.','noun','math_en','geometry'),
('E','edge','모서리','A cube has 12 edges.','정육면체는 12개의 모서리를 가지고 있습니다.','noun','math_en','geometry'),
('E','face','면','A die has six faces.','주사위는 여섯 개의 면을 가지고 있습니다.','noun','math_en','geometry'),
('E','height','높이','The height of the pyramid is measured from the apex to the center of the base.','피라미드의 높이는 꼭대기에서 밑면의 중심까지 측정됩니다.','noun','math_en','geometry'),
('E','acute angle','예각','An acute angle is less than 90 degrees.','예각은 90도보다 작습니다.','noun phrase','math_en','geometry'),
('E','obtuse angle','둔각','An obtuse angle is greater than 90 degrees but less than 180 degrees.','둔각은 90도보다 크고 180도보다 작습니다.','noun phrase','math_en','geometry'),
('E','right angle','직각','The corner of a book is a right angle.','책의 모퉁이는 직각입니다.','noun phrase','math_en','geometry'),
('E','straight angle','평각','A straight angle measures 180 degrees.','평각은 180도를 측정합니다.','noun phrase','math_en','geometry'),
('E','reflex angle','반사각','A reflex angle is greater than 180 degrees.','반사각은 180도보다 큽니다.','noun phrase','math_en','geometry'),
('E','isosceles triangle','이등변삼각형','An isosceles triangle has two equal sides and two equal angles.','이등변삼각형은 두 변과 두 각이 같습니다.','noun phrase','math_en','geometry'),
('E','scalene triangle','부등변삼각형','A scalene triangle has no equal sides or angles.','부등변삼각형은 같은 변이나 각이 없습니다.','noun phrase','math_en','geometry'),
('E','quadrilateral','사각형','A square is a special type of quadrilateral.','정사각형은 특별한 종류의 사각형입니다.','noun','math_en','geometry'),
('E','rhombus','마름모','A rhombus has four equal sides.','마름모는 네 변의 길이가 같습니다.','noun','math_en','geometry'),
('E','trapezoid','사다리꼴','A trapezoid has at least one pair of parallel sides.','사다리꼴은 적어도 한 쌍의 평행한 변을 가집니다.','noun','math_en','geometry'),
('E','cone','원뿔','The volume of a cone is one-third the area of the base times the height.','원뿔의 부피는 밑면 넓이 곱하기 높이의 3분의 1입니다.','noun','math_en','geometry'),
('E','cylinder','원기둥','The volume of a cylinder is the area of the base times the height.','원기둥의 부피는 밑면 넓이 곱하기 높이입니다.','noun','math_en','geometry'),
('E','sphere','구','A sphere is a perfectly round geometrical object in three-dimensional space.','구는 3차원 공간에서 완벽하게 둥근 기하학적 객체입니다.','noun','math_en','geometry'),
('E','Probability','확률','The probability of rolling a 6 on a fair die is 1/6.','공정한 주사위를 굴려 6이 나올 확률은 1/6입니다.','noun','math_en','stats'),
('E','Mean','평균','The mean score on the test was 85.','시험 점수의 평균은 85점이었습니다.','noun','math_en','stats'),
('E','Median','중앙값','The median age of the participants was 25.','참가자들의 중앙 연령은 25세였습니다.','noun','math_en','stats'),
('E','Mode','최빈값','The mode of the dataset is the number that appears most frequently.','데이터셋의 최빈값은 가장 자주 나타나는 숫자입니다.','noun','math_en','stats'),
('E','Range','범위','The range of the data is the difference between the highest and lowest values.','데이터의 범위는 가장 높은 값과 가장 낮은 값의 차이입니다.','noun','math_en','stats'),
('E','Standard Deviation','표준 편차','A low standard deviation indicates that the data points are close to the mean.','낮은 표준 편차는 데이터 포인트가 평균에 가깝다는 것을 나타냅니다.','noun phrase','math_en','stats'),
('E','Distribution','분포','The histogram shows the distribution of student heights.','히스토그램은 학생들의 키 분포를 보여줍니다.','noun','math_en','stats'),
('E','Sample','표본','We took a random sample of 100 voters.','우리는 100명의 유권자를 무작위로 표본 추출했습니다.','noun','math_en','stats'),
('E','Outcome','결과','Each flip of the coin has two possible outcomes: heads or tails.','각 동전 던지기에는 앞면 또는 뒷면의 두 가지 가능한 결과가 있습니다.','noun','math_en','stats'),
('E','Event','사건','Drawing a red card is an event in a deck of cards.','빨간 카드를 뽑는 것은 카드 덱에서의 한 사건입니다.','noun','math_en','stats'),
('E','Percent','퍼센트, 백분율','Fifty percent of the students passed the exam.','학생들의 50퍼센트가 시험에 합격했습니다.','noun','math_en','stats'),
('E','Average','평균','The average rainfall this month was higher than usual.','이번 달 평균 강우량은 평소보다 많았습니다.','noun','math_en','stats'),
('E','Correlation','상관 관계','There is a strong positive correlation between study time and grades.','공부 시간과 성적 사이에는 강한 양의 상관 관계가 있습니다.','noun','math_en','stats'),
('E','Outlier','이상치','The outlier in the data set significantly skewed the average.','데이터 세트의 이상치가 평균을 상당히 왜곡했습니다.','noun','math_en','stats'),
('E','Bar Chart','막대 그래프','The bar chart shows the sales figures for each month.','막대 그래프는 각 월의 판매 수치를 보여줍니다.','noun phrase','math_en','stats'),
('E','Pie Chart','원 그래프','The pie chart illustrates the budget allocation.','원 그래프는 예산 할당을 보여줍니다.','noun phrase','math_en','stats'),
('E','Histogram','히스토그램','A histogram is used to display the frequency distribution of continuous data.','히스토그램은 연속 데이터의 빈도 분포를 표시하는 데 사용됩니다.','noun','math_en','stats'),
('E','Population','모집단','The study surveyed the entire population of high school students in the city.','그 연구는 도시의 고등학생 전체 모집단을 조사했습니다.','noun','math_en','stats'),
('E','Parameter','모수','The mean and standard deviation are parameters of a normal distribution.','평균과 표준 편차는 정규 분포의 모수입니다.','noun','math_en','stats'),
('E','Statistic','통계치','The sample mean is a statistic used to estimate the population mean.','표본 평균은 모집단 평균을 추정하는 데 사용되는 통계치입니다.','noun','math_en','stats'),
('E','Variance','분산','Variance measures how spread out the data is from the mean.','분산은 데이터가 평균에서 얼마나 퍼져 있는지를 측정합니다.','noun','math_en','stats'),
('E','Random','무작위의','A random selection ensures that each item has an equal chance of being chosen.','무작위 선택은 각 항목이 선택될 동등한 기회를 갖도록 보장합니다.','adjective','math_en','stats'),
('E','Inference','추론','Statistical inference allows us to draw conclusions about a population from a sample.','통계적 추론은 표본으로부터 모집단에 대한 결론을 도출할 수 있게 합니다.','noun','math_en','stats'),
('E','Regression','회귀','Regression analysis helps predict one variable based on another.','회귀 분석은 다른 변수에 기초하여 한 변수를 예측하는 데 도움이 됩니다.','noun','math_en','stats'),
('E','equation','방정식','Solve the equation x + 5 = 10.','방정식 x + 5 = 10을 푸시오.','noun','math_en',NULL),
('E','variable','변수','In the equation, x is the variable.','방정식에서 x는 변수입니다.','noun','math_en',NULL),
('E','fraction','분수','1/2 is a simple fraction.','1/2은 간단한 분수입니다.','noun','math_en',NULL),
('E','numerator','분자','The numerator is the top part of a fraction.','분자는 분수의 윗부분입니다.','noun','math_en',NULL),
('E','denominator','분모','The denominator is the bottom part of a fraction.','분모는 분수의 아랫부분입니다.','noun','math_en',NULL),
('E','exponent','지수','In x^2, 2 is the exponent.','x^2에서 2는 지수입니다.','noun','math_en',NULL),
('E','coefficient','계수','The coefficient of 3x is 3.','3x의 계수는 3입니다.','noun','math_en',NULL),
('E','polynomial','다항식','x^2 + 2x + 1 is a polynomial.','x^2 + 2x + 1은 다항식입니다.','noun','math_en',NULL),
('E','factor','인수, 약수','2 and 3 are factors of 6.','2와 3은 6의 인수입니다.','noun','math_en',NULL),
('E','slope','기울기','The slope of the line is 2.','직선의 기울기는 2입니다.','noun','math_en',NULL),
('E','ratio','비율','The ratio of boys to girls is 1:2.','남학생 대 여학생의 비율은 1:2입니다.','noun','math_en',NULL),
('E','probability','확률','The probability of rolling a 6 is 1/6.','6을 굴릴 확률은 1/6입니다.','noun','math_en',NULL),
('E','geometry','기하학','Geometry studies shapes and space.','기하학은 도형과 공간을 연구합니다.','noun','math_en',NULL),
('E','theorem','정리 (수학)','The Pythagorean theorem relates the sides of a right triangle.','피타고라스 정리는 직각삼각형의 변의 길이를 관련시킵니다.','noun','math_en',NULL),
('E','hypotenuse','빗변','The hypotenuse is the longest side of a right triangle.','빗변은 직각삼각형에서 가장 긴 변입니다.','noun','math_en',NULL),
('E','angle','각','The angle in the corner is 90 degrees.','모서리의 각은 90도입니다.','noun','math_en',NULL),
('E','derivative','미분','The derivative measures the rate of change.','미분은 변화율을 측정합니다.','noun','math_en',NULL),
('E','integral','적분','Integral calculus deals with areas under curves.','적분학은 곡선 아래의 넓이를 다룹니다.','noun','math_en',NULL),
('E','sum','합','The sum of 2 and 3 is 5.','2와 3의 합은 5입니다.','noun','math_en',NULL),
('E','product','곱','The product of 4 and 5 is 20.','4와 5의 곱은 20입니다.','noun','math_en',NULL),
('E','average','평균','The average score was 85.','평균 점수는 85점이었습니다.','noun','math_en',NULL),
('E','median','중앙값','The median is the middle value in a sorted list.','중앙값은 정렬된 목록에서 가운데 값입니다.','noun','math_en',NULL),
('E','mode','최빈값','The mode is the most frequent value.','최빈값은 가장 자주 나타나는 값입니다.','noun','math_en',NULL),
('E','root','근 (방정식)','The root of x - 3 = 0 is 3.','x - 3 = 0의 근은 3입니다.','noun','math_en',NULL),
('E','square root','제곱근','The square root of 9 is 3.','9의 제곱근은 3입니다.','noun phrase','math_en',NULL),
('E','cube root','세제곱근','The cube root of 8 is 2.','8의 세제곱근은 2입니다.','noun phrase','math_en',NULL),
('E','percentage','백분율','50% is half of the total.','50%는 전체의 절반입니다.','noun','math_en',NULL),
('E','decimal','소수','0.5 is the decimal for 1/2.','0.5는 1/2의 소수입니다.','noun','math_en',NULL),
('E','integer','정수','Integers include positive and negative whole numbers.','정수에는 양수와 음수 정수가 포함됩니다.','noun','math_en',NULL),
('E','coordinate','좌표','The coordinate (2, 3) is in the first quadrant.','좌표 (2, 3)은 제1사분면에 있습니다.','noun','math_en',NULL),
('E','axis','축 (좌표)','The x-axis is horizontal.','x축은 수평입니다.','noun','math_en',NULL),
('E','function','함수','f(x) = 2x is a linear function.','f(x) = 2x는 일차 함수입니다.','noun','math_en',NULL),
('E','graph','그래프','Draw the graph of the function.','함수의 그래프를 그리시오.','noun','math_en',NULL),
('E','set','집합','The set of even numbers is {2, 4, 6, ...}.','짝수의 집합은 {2, 4, 6, ...}입니다.','noun','math_en',NULL),
('E','element','원소 (집합)','3 is an element of the set {1, 2, 3}.','3은 집합 {1, 2, 3}의 원소입니다.','noun','math_en',NULL),
('E','formula','공식','The area of a circle is given by the formula A = πr^2.','원의 넓이는 공식 A = πr^2으로 주어집니다.','noun','math_en',NULL),
('E','calculate','계산하다','Calculate the total cost.','총 비용을 계산하시오.','verb','math_en',NULL),
('E','measure','측정하다','Measure the length of the side.','변의 길이를 측정하시오.','verb','math_en',NULL),
('E','simplify','간단히 하다','Simplify the expression 2x + 3x.','식 2x + 3x를 간단히 하시오.','verb','math_en',NULL),
('E','prove','증명하다','Prove that the sum of angles in a triangle is 180 degrees.','삼각형 내각의 합이 180도임을 증명하시오.','verb','math_en',NULL),
('E','diagram','도표, 그림','Draw a diagram to illustrate the problem.','문제를 설명하기 위해 도표를 그리시오.','noun','math_en',NULL),
('E','circumference','원주','The circumference of a circle is 2πr.','원의 원주는 2πr입니다.','noun','math_en',NULL),
('E','area','넓이','The area of the square is side * side.','정사각형의 넓이는 변 * 변입니다.','noun','math_en',NULL),
('E','volume','부피','Calculate the volume of the box.','상자의 부피를 계산하시오.','noun','math_en',NULL),
('E','parallel','평행의','Parallel lines never intersect.','평행선은 절대 만나지 않습니다.','adjective','math_en',NULL),
('E','perpendicular','수직의','Perpendicular lines intersect at a 90-degree angle.','수직선은 90도 각도로 만납니다.','adjective','math_en',NULL),
('E','absolute value','절댓값','The absolute value of -5 is 5.','-5의 절댓값은 5입니다.','noun phrase','math_en',NULL),
('E','Abundant','풍부한, 많은','The region is abundant in natural resources.','그 지역은 천연자원이 풍부하다.','adjective','sat','easy'),
('E','Adequate','적절한, 충분한','We have adequate supplies for the trip.','우리는 여행에 필요한 물품이 충분하다.','adjective','sat','easy'),
('E','Analyze','분석하다','We need to analyze the data to find a solution.','해결책을 찾기 위해 데이터를 분석해야 한다.','verb','sat','easy'),
('E','Apparent','분명한, 명백한','It was apparent that he was lying.','그가 거짓말을 하고 있다는 것은 분명했다.','adjective','sat','easy'),
('E','Assert','단언하다, 주장하다','He asserted that he was innocent.','그는 자신이 무죄라고 단언했다.','verb','sat','easy'),
('E','Attribute','속성, 특성; ~의 탓으로 돌리다','Her success is due to her hard work and a positive attitude.','그녀의 성공은 그녀의 노력과 긍정적인 태도 덕분이다.','noun/verb','sat','easy'),
('E','Bias','편견, 편향','The study was criticized for its potential bias.','그 연구는 잠재적인 편견 때문에 비판받았다.','noun','sat','easy'),
('E','Bolster','강화하다, 지지하다','The new evidence will bolster our case.','새로운 증거가 우리의 주장을 강화할 것이다.','verb','sat','easy'),
('E','Circumstance','상황, 환경','Under normal circumstances, the event would have been cancelled.','정상적인 상황이라면 그 행사는 취소되었을 것이다.','noun','sat','easy'),
('E','Coherent','일관성 있는, 논리적인','His argument was clear and coherent.','그의 주장은 명확하고 일관성 있었다.','adjective','sat','easy'),
('E','Complement','보완하다, 칭찬하다','The wine complements the meal perfectly.','그 와인은 식사와 완벽하게 어울린다.','verb','sat','easy'),
('E','Constitute','구성하다, ~이 되다','Women constitute about half of the workforce.','여성은 노동력의 약 절반을 구성한다.','verb','sat','easy'),
('E','Contradict','모순되다, 반박하다','His statement contradicts his previous testimony.','그의 진술은 이전 증언과 모순된다.','verb','sat','easy'),
('E','Corroborate','입증하다, 확증하다','Can you corroborate his alibi?','그의 알리바이를 입증해 줄 수 있습니까?','verb','sat','easy'),
('E','Crucial','중대한, 결정적인','This is a crucial moment for our team.','이것은 우리 팀에게 결정적인 순간이다.','adjective','sat','easy'),
('E','Delineate','상세하게 묘사하다, 윤곽을 그리다','The report delineates the steps needed to complete the project.','보고서는 프로젝트 완료에 필요한 단계를 상세히 묘사한다.','verb','sat','easy'),
('E','Depict','묘사하다, 그리다','The painting depicts a serene landscape.','그 그림은 고요한 풍경을 묘사한다.','verb','sat','easy'),
('E','Deter','단념시키다, 막다','The high price will deter many customers.','높은 가격은 많은 고객들의 구매를 단념시킬 것이다.','verb','sat','easy'),
('E','Discrepancy','불일치, 차이','There is a discrepancy between the two reports.','두 보고서 사이에 불일치가 있다.','noun','sat','easy'),
('E','Disseminate','퍼뜨리다, 전파하다','The goal is to disseminate information widely.','목표는 정보를 널리 퍼뜨리는 것이다.','verb','sat','easy'),
('E','Diverse','다양한','The city has a diverse population.','그 도시는 다양한 인구를 가지고 있다.','adjective','sat','easy'),
('E','Emphasize','강조하다','The teacher emphasized the importance of studying.','선생님은 공부의 중요성을 강조했다.','verb','sat','easy'),
('E','Endorse','지지하다, 보증하다','The celebrity endorsed the new product.','그 유명인은 신제품을 보증했다.','verb','sat','easy'),
('E','Enhance','향상시키다, 개선하다','Good lighting can enhance the appearance of a room.','좋은 조명은 방의 외관을 향상시킬 수 있다.','verb','sat','easy'),
('E','Equivocal','모호한, 애매한','His response was equivocal, leaving us unsure of his true feelings.','그의 대답은 모호해서 그의 진심을 확신할 수 없었다.','adjective','sat','easy'),
('E','Explicit','명백한, 분명한','The instructions were explicit and easy to follow.','지침은 명백하고 따라하기 쉬웠다.','adjective','sat','easy'),
('E','Facilitate','촉진하다, 용이하게 하다','Technology can facilitate communication.','기술은 소통을 촉진할 수 있다.','verb','sat','easy'),
('E','Feasible','실현 가능한, 실행 가능한','Is it feasible to complete the project by Friday?','금요일까지 프로젝트를 완료하는 것이 실행 가능합니까?','adjective','sat','easy'),
('E','Furthermore','더욱이, 게다가','The plan is too expensive. Furthermore, it is unlikely to succeed.','그 계획은 너무 비싸다. 더욱이, 성공할 가능성도 낮다.','adverb','sat','easy'),
('E','acrimonious','신랄한, 격렬한 (말)','The debate became acrimonious as the candidates attacked each other''s records.','후보자들이 서로의 경력을 공격하면서 토론은 격렬해졌다.','adjective','sat','hard'),
('E','ameliorate','개선하다, 좋아지게 하다','The new policy aims to ameliorate the living conditions of the poor.','새로운 정책은 빈곤층의 생활 여건을 개선하는 것을 목표로 한다.','verb','sat','hard'),
('E','anachronism','시대착오','A horse-drawn carriage in the middle of a modern city is an anachronism.','현대 도시 한복판의 마차는 시대착오이다.','noun','sat','hard'),
('E','apocryphal','거짓의, 출처가 불분명한','The story of George Washington chopping down a cherry tree is apocryphal.','조지 워싱턴이 체리 나무를 베었다는 이야기는 출처가 불분명하다.','adjective','sat','hard'),
('E','arcane','비밀의, 불가사의한','The rituals of the secret society were arcane and mysterious.','그 비밀 결사의 의식은 비밀스럽고 신비로웠다.','adjective','sat','hard'),
('E','assiduous','성실한, 근면한','She was an assiduous student, always completing her assignments on time.','그녀는 항상 과제를 제시간에 완료하는 성실한 학생이었다.','adjective','sat','hard'),
('E','bellicose','호전적인, 싸우기 좋아하는','His bellicose attitude often led to arguments.','그의 호전적인 태도는 종종 논쟁을 야기했다.','adjective','sat','hard'),
('E','bucolic','전원적인, 시골의','The painting depicted a peaceful, bucolic landscape.','그 그림은 평화롭고 전원적인 풍경을 묘사했다.','adjective','sat','hard'),
('E','calumny','비방, 중상','The politician was accused of calumny for spreading false rumors.','그 정치인은 거짓 소문을 퍼뜨린 혐의로 비방죄로 기소되었다.','noun','sat','hard'),
('E','chicanery','속임수, 교묘한 술책','The lawyer used legal chicanery to delay the trial.','그 변호사는 재판을 지연시키기 위해 법적인 교묘한 술책을 사용했다.','noun','sat','hard'),
('E','circumspect','신중한, 조심성 있는','Given the sensitive nature of the information, she was very circumspect in her statements.','정보의 민감한 특성을 고려할 때, 그녀는 진술에 매우 신중했다.','adjective','sat','hard'),
('E','cogent','설득력 있는, 타당한','The scientist presented a cogent argument for her hypothesis.','그 과학자는 자신의 가설에 대한 설득력 있는 주장을 제시했다.','adjective','sat','hard'),
('E','deleterious','해로운, 유해한','Smoking has deleterious effects on lung health.','흡연은 폐 건강에 해로운 영향을 미친다.','adjective','sat','hard'),
('E','disparate','서로 다른, 공통점이 없는','The two studies examined disparate aspects of the same problem.','두 연구는 동일한 문제의 서로 다른 측면을 조사했다.','adjective','sat','hard'),
('E','egregious','지독한, 터무니없는','The company''s egregious violation of environmental laws led to a massive fine.','회사의 환경법에 대한 지독한 위반은 막대한 벌금으로 이어졌다.','adjective','sat','hard'),
('E','elucidate','설명하다, 명료하게 하다','The professor tried to elucidate the complex theory.','교수님은 복잡한 이론을 명료하게 설명하려고 노력했다.','verb','sat','hard'),
('E','emollient','피부를 부드럽게 하는, 진정시키는','The lotion contained an emollient to soothe dry skin.','로션에는 건조한 피부를 진정시키는 유연제가 포함되어 있었다.','adjective','sat','hard'),
('E','enervate','기운을 빼앗다, 약화시키다','The long journey served to enervate the travelers.','긴 여정은 여행자들의 기운을 빼앗았다.','verb','sat','hard'),
('E','ephemeral','덧없는, 일시적인','The beauty of the cherry blossoms is ephemeral.','벚꽃의 아름다움은 덧없다.','adjective','sat','hard'),
('E','equivocate','모호하게 말하다, 얼버무리다','When asked about his involvement, he began to equivocate.','그의 연루에 대해 질문받았을 때, 그는 얼버무리기 시작했다.','verb','sat','hard'),
('E','erudite','박식한, 학식 있는','The erudite scholar could discuss any topic with great knowledge.','그 박식한 학자는 어떤 주제에 대해서도 많은 지식으로 토론할 수 있었다.','adjective','sat','hard'),
('E','eschew','피하다, 삼가다','He decided to eschew violence as a means of protest.','그는 항의 수단으로 폭력을 피하기로 결정했다.','verb','sat','hard'),
('E','eulogy','찬사, 추도사','She delivered a heartfelt eulogy at her grandfather''s funeral.','그녀는 할아버지의 장례식에서 진심 어린 추도사를 했다.','noun','sat','hard'),
('E','exacerbate','악화시키다','His harsh words only served to exacerbate the conflict.','그의 거친 말은 갈등을 악화시킬 뿐이었다.','verb','sat','hard'),
('E','exculpate','무죄를 입증하다, 혐의를 벗기다','New evidence emerged that exculpated the suspect.','용의자의 혐의를 벗겨주는 새로운 증거가 나타났다.','verb','sat','hard'),
('E','fastidious','까다로운, 꼼꼼한','He is fastidious about his appearance, always wearing perfectly ironed clothes.','그는 항상 완벽하게 다려진 옷을 입으며 외모에 대해 매우 꼼꼼하다.','adjective','sat','hard'),
('E','fecund','다산의, 비옥한, 상상력이 풍부한','The fertile soil was known for producing fecund crops.','그 비옥한 토양은 풍성한 작물을 생산하는 것으로 알려져 있었다.','adjective','sat','hard'),
('E','foment','조장하다, 선동하다','The rumors were intended to foment unrest among the citizens.','그 소문들은 시민들 사이에 불만을 조장하기 위한 것이었다.','verb','sat','hard'),
('E','garrulous','수다스러운, 장황한','My garrulous neighbor can talk for hours about nothing.','나의 수다스러운 이웃은 아무것도 아닌 것에 대해 몇 시간이고 이야기할 수 있다.','adjective','sat','hard'),
('E','halcyon','평온한, 행복했던','She reminisced about the halcyon days of her youth.','그녀는 젊은 시절의 평온했던 날들을 회상했다.','adjective','sat','hard'),
('E','hegemony','패권, 주도권','The country sought to establish regional hegemony.','그 나라는 지역 패권을 확립하려고 했다.','noun','sat','hard'),
('E','iconoclast','우상 파괴자, 인습 타파주의자','She was an iconoclast who challenged traditional beliefs.','그녀는 전통적인 믿음에 도전하는 인습 타파주의자였다.','noun','sat','hard'),
('E','ignominious','수치스러운, 불명예스러운','The team suffered an ignominious defeat in the championship game.','그 팀은 챔피언십 경기에서 수치스러운 패배를 겪었다.','adjective','sat','hard'),
('E','impassive','무표정한, 감정을 드러내지 않는','He remained impassive despite the shocking news.','그는 충격적인 소식에도 불구하고 무표정했다.','adjective','sat','hard'),
('E','impecunious','가난한, 돈이 없는','The impecunious artist struggled to make ends meet.','가난한 예술가는 생계를 유지하기 위해 고군분투했다.','adjective','sat','hard'),
('E','imperturbable','침착한, 동요하지 않는','The captain remained imperturbable during the crisis.','선장은 위기 동안 침착함을 유지했다.','adjective','sat','hard'),
('E','inchoate','초기의, 불완전한','His plan was still inchoate and needed further development.','그의 계획은 아직 초기 단계였고 더 많은 발전이 필요했다.','adjective','sat','hard'),
('E','incongruous','일치하지 않는, 조화롭지 못한','The bright pink sofa looked incongruous in the otherwise minimalist room.','밝은 분홍색 소파는 그 외의 미니멀리스트적인 방과 조화롭지 못했다.','adjective','sat','hard'),
('E','abate','약해지다, 줄이다','The storm began to abate after several hours.','폭풍은 몇 시간 후에 약해지기 시작했다.','verb','sat','medium'),
('E','abdicate','퇴위하다, 포기하다','The king was forced to abdicate his throne.','왕은 왕위에서 퇴위하도록 강요받았다.','verb','sat','medium'),
('E','aberration','일탈, 이상','The sudden drop in temperature was an aberration for this time of year.','갑작스러운 기온 하강은 이 시기에는 이례적인 일이었다.','noun','sat','medium'),
('E','abhor','혐오하다, 증오하다','She abhors violence and injustice.','그녀는 폭력과 불의를 혐오한다.','verb','sat','medium'),
('E','abide','묵다, 견디다, 따르다','You must abide by the rules.','당신은 규칙을 따라야 합니다.','verb','sat','medium'),
('E','abjure','맹세하고 버리다, 포기하다','He had to abjure his former beliefs.','그는 이전의 신념을 맹세하고 버려야 했다.','verb','sat','medium'),
('E','abnegate','권리 등을 포기하다, 부정하다','She decided to abnegate her personal desires for the sake of her family.','그녀는 가족을 위해 자신의 개인적인 욕망을 포기하기로 결정했다.','verb','sat','medium'),
('E','abound','가득 차다, 풍부하다','Opportunities abound for those willing to work hard.','열심히 일하려는 사람들에게는 기회가 풍부하다.','verb','sat','medium'),
('E','abrogate','폐지하다, 무효로 하다','The treaty was abrogated by mutual consent.','조약은 상호 합의로 폐지되었다.','verb','sat','medium'),
('E','abscond','몰래 도주하다, 종적을 감추다','The treasurer absconded with the company''s funds.','재무 담당자는 회사의 자금을 가지고 몰래 도주했다.','verb','sat','medium'),
('E','abstain','자제하다, 기권하다','He abstained from voting on the controversial issue.','그는 논란이 되는 문제에 대한 투표를 기권했다.','verb','sat','medium'),
('E','abstruse','난해한, 이해하기 어려운','The professor''s lecture on quantum physics was quite abstruse.','양자 물리학에 대한 교수의 강의는 상당히 난해했다.','adjective','sat','medium'),
('E','accede','동의하다, 응하다, 취임하다','The company agreed to accede to the demands.','회사는 요구에 응하기로 동의했다.','verb','sat','medium'),
('E','acclimate','순응하다, 적응시키다','It took him a while to acclimate to the new environment.','그가 새로운 환경에 적응하는 데는 시간이 좀 걸렸다.','verb','sat','medium'),
('E','accolade','찬사, 상','She received many accolades for her groundbreaking research.','그녀는 획기적인 연구로 많은 찬사를 받았다.','noun','sat','medium'),
('E','accommodate','수용하다, 숙박시키다, 편의를 봐주다','The hotel can accommodate up to 200 guests.','그 호텔은 최대 200명의 손님을 수용할 수 있다.','verb','sat','medium'),
('E','accord','일치, 조화, 협정','His actions were not in accord with his words.','그의 행동은 그의 말과 일치하지 않았다.','noun','sat','medium'),
('E','accost','다가서서 말을 걸다','He was accosted by a stranger on the street.','그는 거리에서 낯선 사람에게 말을 걸었다.','verb','sat','medium'),
('E','accrue','증가하다, 축적하다, (이자 등이) 붙다','Interest will accrue on the savings account.','저축 계좌에 이자가 붙을 것이다.','verb','sat','medium'),
('E','acquiesce','묵인하다, 순응하다','She acquiesced to his proposal without much argument.','그녀는 많은 논쟁 없이 그의 제안에 묵인했다.','verb','sat','medium'),
('E','acquit','무죄를 선고하다','The jury acquitted the defendant of all charges.','배심원단은 피고인에게 모든 혐의에 대해 무죄를 선고했다.','verb','sat','medium'),
('E','acrid','매운, 신랄한, 격렬한','The acrid smell of burning rubber filled the air.','타는 고무의 매캐한 냄새가 공기를 가득 채웠다.','adjective','sat','medium'),
('E','acrimony','신랄함, 격함','The divorce was finalized with considerable acrimony.','이혼은 상당한 격앙 속에서 마무리되었다.','noun','sat','medium'),
('E','acumen','통찰력, 예리함','Her business acumen is impressive.','그녀의 사업적 통찰력은 인상적이다.','noun','sat','medium'),
('E','adage','속담, 격언','As the old adage goes, ''Honesty is the best policy.''','오래된 격언처럼, ''정직이 최선의 방책이다.''','noun','sat','medium'),
('E','adroit','능숙한, 재치 있는','He made an adroit move to escape the trap.','그는 함정에서 벗어나기 위해 능숙한 움직임을 보였다.','adjective','sat','medium'),
('E','adulation','아첨, 과찬','The singer enjoyed the adulation of his fans.','그 가수는 팬들의 과찬을 즐겼다.','noun','sat','medium'),
('E','adulterate','불순하게 하다, 품질을 떨어뜨리다','The manufacturer was accused of adulterating the product with cheaper ingredients.','제조업자는 더 저렴한 재료로 제품을 불순하게 했다는 비난을 받았다.','verb','sat','medium'),
('E','adverse','부정적인, 불리한','The company faced adverse criticism for its environmental policies.','회사는 환경 정책에 대해 부정적인 비판에 직면했다.','adjective','sat','medium'),
('E','advocate','옹호하다, 지지하다','She is a strong advocate for animal rights.','그녀는 동물 권리를 강력하게 옹호하는 사람이다.','verb','sat','medium'),
('E','aegis','보호, 후원','The project is under the aegis of the United Nations.','그 프로젝트는 유엔의 보호 아래 있다.','noun','sat','medium'),
('E','aesthetic','미학의, 미적인','The architect focused on the aesthetic appeal of the building.','건축가는 건물의 미적인 매력에 집중했다.','adjective','sat','medium'),
('E','affable','상냥한, 친절한','He was an affable man, easy to talk to.','그는 이야기하기 쉬운 상냥한 남자였다.','adjective','sat','medium'),
('E','affinity','친밀감, 유사성','She felt an immediate affinity with the new colleague.','그녀는 새 동료에게 즉각적인 친밀감을 느꼈다.','noun','sat','medium'),
('E','affluent','풍족한, 부유한','They lived in an affluent neighborhood.','그들은 부유한 동네에 살았다.','adjective','sat','medium'),
('E','aggrandize','확대하다, 과장하다','He tried to aggrandize his achievements.','그는 자신의 업적을 과장하려고 했다.','verb','sat','medium'),
('E','alacrity','민첩함, 활기','She accepted the invitation with alacrity.','그녀는 민첩하게 초대를 수락했다.','noun','sat','medium'),
('E','alleviate','완화하다, 경감하다','The medication helped to alleviate his pain.','그 약은 그의 고통을 완화하는 데 도움이 되었다.','verb','sat','medium'),
('E','allude','암시하다, 언급하다','The speaker alluded to the recent political events.','연사는 최근의 정치적 사건들을 암시했다.','verb','sat','medium'),
('E','altruistic','이타적인','His altruistic nature made him a beloved figure.','그의 이타적인 성품은 그를 사랑받는 인물로 만들었다.','adjective','sat','medium'),
('E','Ambiguous','애매모호한, 여러 가지로 해석될 수 있는','The politician''s statement was deliberately ambiguous, leaving voters unsure of his true intentions.','그 정치인의 발언은 의도적으로 애매모호해서, 유권자들이 그의 진짜 의도를 확신하지 못하게 만들었다.','adj','sat',NULL),
('E','Candid','솔직한, 숨김없는','She gave a candid assessment of the project''s shortcomings.','그녀는 프로젝트의 단점들에 대해 솔직한 평가를 내렸다.','adj','sat',NULL),
('E','Pragmatic','실용적인, 현실적인','Instead of theoretical solutions, he offered a pragmatic approach to the problem.','이론적인 해결책 대신, 그는 문제에 대한 실용적인 접근법을 제시했다.','adj','sat',NULL),
('E','Scrutinize','자세히 조사하다, 면밀히 검토하다','The auditor had to scrutinize every financial record to find the discrepancy.','감사관은 불일치를 찾기 위해 모든 재무 기록을 자세히 조사해야 했다.','verb','sat',NULL),
('E','Undermine','약화시키다, 훼손하다','Constant criticism can undermine a person''s confidence.','끊임없는 비판은 사람의 자신감을 약화시킬 수 있다.','verb','sat',NULL),
('E','Advocate','지지하다, 옹호하다 (verb); 지지자, 옹호자 (noun)','She will advocate for stricter environmental regulations.','그녀는 더 엄격한 환경 규제를 옹호할 것이다.','verb','sat',NULL),
('E','Nuance','미묘한 차이, 뉘앙스','The painting captured every nuance of the sunset''s colors.','그 그림은 해질녘 색깔의 모든 미묘한 차이를 포착했다.','noun','sat',NULL),
('E','Arbitrary','임의의, 자의적인','The decision to change the schedule seemed arbitrary and unfair.','일정을 변경하기로 한 결정은 자의적이고 불공평해 보였다.','adj','sat',NULL),
('E','Diligent','성실한, 근면한','A diligent student, she always completed her assignments on time.','성실한 학생으로서, 그녀는 항상 과제를 제시간에 완료했다.','adj','sat',NULL),
('E','Eloquent','유창한, 설득력 있는 (말을 잘하는)','His eloquent speech moved the audience to tears.','그의 유창한 연설은 청중을 감동시켜 눈물을 흘리게 했다.','adj','sat',NULL),
('E','Ephemeral','덧없는, 일시적인','The beauty of the cherry blossoms is ephemeral, lasting only a few weeks.','벚꽃의 아름다움은 덧없어서, 불과 몇 주밖에 지속되지 않는다.','adj','sat',NULL),
('E','Gregarious','사교적인, 군집성의','He was a gregarious person who loved being surrounded by friends.','그는 친구들에게 둘러싸여 있기를 좋아하는 사교적인 사람이었다.','adj','sat',NULL),
('E','Hypothesis','가설','The scientist developed a hypothesis to explain the strange phenomenon.','그 과학자는 이상한 현상을 설명하기 위한 가설을 세웠다.','noun','sat',NULL),
('E','Inherent','내재하는, 본질적인','There is an inherent risk in investing in the stock market.','주식 시장에 투자하는 것에는 내재된 위험이 있다.','adj','sat',NULL),
('E','Meticulous','꼼꼼한, 세심한','She was meticulous in her preparation for the exam, reviewing every detail.','그녀는 모든 세부 사항을 검토하며 시험 준비에 꼼꼼했다.','adj','sat',NULL),
('E','Nostalgia','향수, 노스탤지어','Looking at old photos filled him with nostalgia for his childhood.','오래된 사진을 보는 것은 그에게 어린 시절에 대한 향수를 불러일으켰다.','noun','sat',NULL),
('E','Ostentatious','과시하는, 허세를 부리는','He drove an ostentatious sports car, clearly wanting to attract attention.','그는 시선을 끌고 싶어 하는 것이 분명한 과시적인 스포츠카를 운전했다.','adj','sat',NULL),
('E','Pensive','수심에 잠긴, 생각에 잠긴','She sat by the window, looking pensive as she reflected on her future.','그녀는 창가에 앉아 미래를 숙고하며 생각에 잠긴 듯 보였다.','adj','sat',NULL),
('E','Plausible','그럴듯한, 타당한','His explanation for being late was plausible, though not entirely convincing.','그가 늦은 이유에 대한 설명은 완전히 설득력 있지는 않았지만 그럴듯했다.','adj','sat',NULL),
('E','Resilient','회복력 있는, 탄력 있는','Children are often more resilient than adults after facing difficulties.','아이들은 어려움에 직면한 후 성인보다 회복력이 있는 경우가 많다.','adj','sat',NULL),
('E','Ubiquitous','어디에나 있는, 아주 흔한','Smartphones have become ubiquitous in modern society.','스마트폰은 현대 사회에서 어디에나 있는 것이 되었다.','adj','sat',NULL),
('E','Vindicate','무죄를 입증하다, 정당성을 입증하다','The DNA evidence eventually vindicated the wrongly accused man.','DNA 증거는 결국 잘못 기소된 남자의 무죄를 입증했다.','verb','sat',NULL),
('E','Wane','약해지다, 줄어들다','Support for the policy began to wane as its costs became apparent.','정책의 비용이 분명해지면서 그 정책에 대한 지지가 약해지기 시작했다.','verb','sat',NULL),
('E','Abdicate','권리를 포기하다, 퇴위하다','The king was forced to abdicate the throne due to public pressure.','왕은 대중의 압력으로 인해 왕좌에서 퇴위해야 했다.','verb','sat',NULL),
('E','Acquiesce','묵인하다, 순응하다','He finally acquiesced to their demands after much argument.','그는 많은 논쟁 끝에 결국 그들의 요구에 묵인했다.','verb','sat',NULL),
('E','Alleviate','완화시키다, 경감시키다','The medicine helped to alleviate her pain.','그 약은 그녀의 고통을 완화시키는 데 도움이 되었다.','verb','sat',NULL),
('E','Anachronism','시대착오','A horse-drawn carriage in the middle of a bustling modern city is an anachronism.','붐비는 현대 도시 한복판의 마차는 시대착오이다.','noun','sat',NULL),
('E','Assiduous','근면한, 끈기 있는','The assiduous researcher spent years collecting data.','그 근면한 연구원은 수년간 데이터를 수집하는 데 보냈다.','adj','sat',NULL),
('E','Benevolent','자비로운, 인정 많은','The benevolent dictator was surprisingly kind to his subjects.','그 자비로운 독재자는 백성들에게 놀랍도록 친절했다.','adj','sat',NULL),
('E','Capricious','변덕스러운','His capricious behavior made it difficult to predict his next move.','그의 변덕스러운 행동 때문에 다음 행동을 예측하기 어려웠다.','adj','sat',NULL),
('E','Concede','인정하다, 양보하다','After reviewing the evidence, the lawyer had to concede that his client was guilty.','증거를 검토한 후, 변호사는 의뢰인이 유죄라는 것을 인정해야 했다.','verb','sat',NULL),
('E','Deference','존중, 경의','He spoke with deference to his elders.','그는 연장자들에게 존중을 표하며 말했다.','noun','sat',NULL),
('E','Disparage','깎아내리다, 폄하하다','It is unprofessional to disparage your colleagues'' work.','동료들의 일을 깎아내리는 것은 비전문적이다.','verb','sat',NULL),
('E','Elucidate','설명하다, 명료하게 하다','The professor used diagrams to elucidate the complex theory.','교수는 복잡한 이론을 설명하기 위해 도표를 사용했다.','verb','sat',NULL),
('E','Enervate','기력을 빼앗다, 약화시키다','The intense heat of the desert can enervate even the strongest traveler.','사막의 강렬한 열기는 가장 강한 여행자조차 기력을 빼앗을 수 있다.','verb','sat',NULL),
('E','Equivocate','애매하게 말하다, 모호하게 말하다','When asked about his involvement, he tended to equivocate.','그의 연루에 대해 물었을 때, 그는 애매하게 말하는 경향이 있었다.','verb','sat',NULL),
('E','Exacerbate','악화시키다','Pouring water on a grease fire will only exacerbate the situation.','기름 화재에 물을 붓는 것은 상황을 악화시킬 뿐이다.','verb','sat',NULL),
('E','Fastidious','까다로운, 꼼꼼한','He is fastidious about his appearance, always dressing perfectly.','그는 외모에 까다로워서 항상 완벽하게 옷을 차려입는다.','adj','sat',NULL),
('E','Furtive','몰래 하는, 은밀한','He cast a furtive glance at the clock, hoping no one would notice.','그는 아무도 눈치채지 못하길 바라며 시계를 힐끗 훔쳐보았다.','adj','sat',NULL),
('E','Immutable','불변의, 변경할 수 없는','The laws of physics are considered immutable.','물리학의 법칙은 불변하는 것으로 간주된다.','adj','sat',NULL),
('E','Indifferent','무관심한, 냉담한','She seemed indifferent to the outcome of the game.','그녀는 경기의 결과에 무관심한 듯 보였다.','adj','sat',NULL),
('E','Inert','비활성의, 움직이지 않는','After the long journey, the cat lay inert on the rug.','긴 여정 후, 고양이는 깔개 위에 비활성 상태로 누워 있었다.','adj','sat',NULL),
('E','Innate','타고난, 선천적인','Creativity is an innate talent for some people.','창의성은 어떤 사람들에게는 타고난 재능이다.','adj','sat',NULL),
('E','Lethargic','무기력한, 졸린','The hot weather made him feel lethargic and unwilling to move.','더운 날씨 때문에 그는 무기력하고 움직이기 싫었다.','adj','sat',NULL),
('E','Loquacious','말이 많은, 수다스러운','She was a loquacious companion, always ready with a story.','그녀는 항상 이야깃거리를 준비하는 말이 많은 동반자였다.','adj','sat',NULL),
('E','Malign','악성의, 해로운 (adj); 비방하다 (verb)','The doctor diagnosed a malign tumor.','의사는 악성 종양을 진단했다.','adj','sat',NULL),
('E','Opaque','불투명한, 이해하기 어려운','The thick fog made the windows opaque.','짙은 안개 때문에 창문이 불투명해졌다.','adj','sat',NULL),
('E','Paradox','역설, 모순','It''s a paradox that the more you study, the less you feel you know.','더 많이 공부할수록 자신이 아는 것이 적다고 느끼는 것은 역설이다.','noun','sat',NULL),
('E','Perfidious','배신하는, 불성실한','His perfidious actions destroyed the trust between them.','그의 배신적인 행동은 그들 사이의 신뢰를 파괴했다.','adj','sat',NULL),
('E','Permeate','스며들다, 퍼지다','The smell of freshly baked bread began to permeate the house.','갓 구운 빵 냄새가 집안에 퍼지기 시작했다.','verb','sat',NULL),
('E','Precocious','조숙한, (아이) 또래보다 발달이 빠른','The precocious child learned to read at the age of three.','조숙한 아이는 세 살 때 글 읽는 법을 배웠다.','adj','sat',NULL),
('E','Prosaic','평범한, 상상력이 없는','His writing style was rather prosaic, lacking imagination.','그의 글쓰기 스타일은 상상력이 부족하여 다소 평범했다.','adj','sat',NULL),
('E','Quell','진압하다, 가라앉히다','The police were able to quell the riot.','경찰은 폭동을 진압할 수 있었다.','verb','sat',NULL),
('E','Reclusive','은둔하는, 외진','After his wife''s death, he became reclusive and rarely left his home.','아내의 죽음 이후, 그는 은둔자가 되어 거의 집을 나서지 않았다.','adj','sat',NULL),
('E','Soporific','졸린, 잠이 오는','The long lecture was soporific, and many students struggled to stay awake.','긴 강의는 졸음을 유발했고, 많은 학생들이 깨어 있으려고 애썼다.','adj','sat',NULL),
('E','Stolid','둔감한, 감정이 없는','Despite the bad news, he remained stolid and showed no emotion.','나쁜 소식에도 불구하고, 그는 둔감하게 남아 있었고 아무런 감정도 보이지 않았다.','adj','sat',NULL),
('E','Subtle','미묘한, 감지하기 어려운','There was a subtle shift in his attitude after the meeting.','회의 후 그의 태도에 미묘한 변화가 있었다.','adj','sat',NULL),
('E','Superfluous','불필요한, 여분의','He tried to cut out any superfluous words from his essay.','그는 에세이에서 불필요한 단어들을 삭제하려고 노력했다.','adj','sat',NULL),
('E','Tenacious','끈질긴, 완고한','The tenacious climber finally reached the summit.','끈질긴 등반가는 마침내 정상에 도달했다.','adj','sat',NULL),
('E','Transient','일시적인, 순간적인','The joy he felt was transient, quickly fading away.','그가 느낀 기쁨은 일시적이어서, 빨리 사라졌다.','adj','sat',NULL),
('E','Vex','화나게 하다, 괴롭히다','The constant delays began to vex the passengers.','끊임없는 지연은 승객들을 화나게 하기 시작했다.','verb','sat',NULL),
('E','Vigilant','경계하는, 빈틈없는','The security guard remained vigilant throughout the night.','경비원은 밤새도록 경계 태세를 유지했다.','adj','sat',NULL),
('E','Vituperative','욕설하는, 통렬한','The politician responded to the criticism with a vituperative attack.','그 정치인은 신랄한 공격으로 비판에 대응했다.','adj','sat',NULL),
('E','Zealous','열심인, 열광적인','He was a zealous supporter of the environmental movement.','그는 환경 운동의 열렬한 지지자였다.','adj','sat',NULL),
('E','cell','세포','The basic unit of all known living organisms is the cell.','모든 알려진 살아있는 유기체의 기본 단위는 세포이다.','noun','science_en','biology'),
('E','organism','유기체, 생물','A bacterium is a single-celled organism.','박테리아는 단세포 유기체이다.','noun','science_en','biology'),
('E','gene','유전자','A gene is a segment of DNA that codes for a specific protein.','유전자는 특정 단백질을 암호화하는 DNA의 일부이다.','noun','science_en','biology'),
('E','DNA','디옥시리보핵산 (DNA)','DNA carries the genetic instructions for the development, functioning, growth and reproduction of all known organisms.','DNA는 모든 알려진 유기체의 발달, 기능, 성장 및 번식을 위한 유전 정보를 담고 있다.','noun','science_en','biology'),
('E','chromosome','염색체','Humans have 23 pairs of chromosomes in each cell.','인간은 각 세포에 23쌍의 염색체를 가지고 있다.','noun','science_en','biology'),
('E','evolution','진화','Evolution explains the diversity of life on Earth.','진화는 지구 생명의 다양성을 설명한다.','noun','science_en','biology'),
('E','photosynthesis','광합성','Plants use photosynthesis to convert light energy into chemical energy.','식물은 광합성을 사용하여 빛 에너지를 화학 에너지로 변환한다.','noun','science_en','biology'),
('E','enzyme','효소','Enzymes are proteins that act as biological catalysts.','효소는 생물학적 촉매 역할을 하는 단백질이다.','noun','science_en','biology'),
('E','tissue','조직','Muscle tissue is responsible for movement.','근육 조직은 운동을 담당한다.','noun','science_en','biology'),
('E','organ','기관, 장기','The heart is a vital organ in the circulatory system.','심장은 순환계의 필수 기관이다.','noun','science_en','biology'),
('E','bacteria','박테리아, 세균','Some bacteria are beneficial, while others can cause disease.','어떤 박테리아는 유익하지만, 다른 박테리아는 질병을 일으킬 수 있다.','noun','science_en','biology'),
('E','virus','바이러스','A virus needs a host cell to replicate.','바이러스는 복제하기 위해 숙주 세포가 필요하다.','noun','science_en','biology'),
('E','ecosystem','생태계','A forest is a complex ecosystem with many interacting species.','숲은 많은 상호 작용하는 종을 가진 복잡한 생태계이다.','noun','science_en','biology'),
('E','species','종','There are millions of different species of organisms on Earth.','지구에는 수백만 종의 다른 유기체가 있다.','noun','science_en','biology'),
('E','mitochondria','미토콘드리아','Mitochondria are often called the powerhouses of the cell.','미토콘드리아는 종종 세포의 발전소라고 불린다.','noun','science_en','biology'),
('E','chloroplast','엽록체','Chloroplasts are where photosynthesis takes place in plant cells.','엽록체는 식물 세포에서 광합성이 일어나는 곳이다.','noun','science_en','biology'),
('E','nucleus','핵','The nucleus contains the cell''s genetic material.','핵은 세포의 유전 물질을 포함한다.','noun','science_en','biology'),
('E','cytoplasm','세포질','Cytoplasm fills the cell and surrounds the organelles.','세포질은 세포를 채우고 세포 소기관을 둘러싼다.','noun','science_en','biology'),
('E','ribosome','리보솜','Ribosomes are responsible for protein synthesis.','리보솜은 단백질 합성을 담당한다.','noun','science_en','biology'),
('E','heredity','유전','Heredity is the passing of traits from parents to offspring.','유전은 부모로부터 자손에게 형질이 전달되는 것이다.','noun','science_en','biology'),
('E','mutation','돌연변이','A mutation is a change in the DNA sequence.','돌연변이는 DNA 서열의 변화이다.','noun','science_en','biology'),
('E','adaptation','적응','Camouflage is an adaptation that helps animals survive.','위장은 동물이 생존하는 데 도움이 되는 적응이다.','noun','science_en','biology'),
('E','natural selection','자연 선택','Natural selection is a key mechanism of evolution.','자연 선택은 진화의 핵심 메커니즘이다.','noun phrase','science_en','biology'),
('E','habitat','서식지','The polar bear''s habitat is the Arctic.','북극곰의 서식지는 북극이다.','noun','science_en','biology'),
('E','predator','포식자','The lion is a predator that hunts zebras.','사자는 얼룩말을 사냥하는 포식자이다.','noun','science_en','biology'),
('E','prey','피식자, 먹이','The rabbit is the fox''s prey.','토끼는 여우의 먹이이다.','noun','science_en','biology'),
('E','symbiosis','공생','The relationship between bees and flowers is an example of symbiosis.','벌과 꽃 사이의 관계는 공생의 예이다.','noun','science_en','biology'),
('E','respiration','호흡','Cellular respiration releases energy from glucose.','세포 호흡은 포도당에서 에너지를 방출한다.','noun','science_en','biology'),
('E','metabolism','신진대사','Metabolism includes all the chemical processes that occur within a living organism.','신진대사는 살아있는 유기체 내에서 일어나는 모든 화학 과정을 포함한다.','noun','science_en','biology'),
('E','pathogen','병원균','A pathogen is a microorganism that causes disease.','병원균은 질병을 일으키는 미생물이다.','noun','science_en','biology'),
('E','antibody','항체','Antibodies are proteins produced by the immune system to neutralize pathogens.','항체는 병원균을 무력화하기 위해 면역계에서 생성되는 단백질이다.','noun','science_en','biology'),
('E','vaccine','백신','Vaccines help the body develop immunity to certain diseases.','백신은 신체가 특정 질병에 대한 면역력을 발달시키는 데 도움이 된다.','noun','science_en','biology'),
('E','genetics','유전학','Genetics is the study of heredity and genes.','유전학은 유전과 유전자에 대한 연구이다.','noun','science_en','biology'),
('E','biotechnology','생명공학','Biotechnology uses living organisms or their products to develop new technologies.','생명공학은 새로운 기술을 개발하기 위해 살아있는 유기체나 그 산물을 사용한다.','noun','science_en','biology'),
('E','biomes','생물 군계','Deserts and rainforests are examples of different biomes.','사막과 열대우림은 서로 다른 생물 군계의 예이다.','noun','science_en','biology'),
('E','atom','원자: 물질을 구성하는 기본 입자.','An atom consists of a nucleus and electrons.','원자는 핵과 전자로 구성된다.','noun','science_en','chemistry'),
('E','molecule','분자: 두 개 이상의 원자가 화학적으로 결합한 집합체.','A water molecule is made of two hydrogen atoms and one oxygen atom.','물 분자는 두 개의 수소 원자와 한 개의 산소 원자로 만들어진다.','noun','science_en','chemistry'),
('E','compound','화합물: 두 종류 이상의 원소가 화학적으로 결합하여 생성된 물질.','Salt is a common compound made of sodium and chlorine.','소금은 나트륨과 염소로 만들어진 흔한 화합물이다.','noun','science_en','chemistry'),
('E','reaction','반응: 화학 물질들이 상호 작용하여 새로운 물질을 형성하는 과정.','The chemical reaction produced heat and light.','그 화학 반응은 열과 빛을 생성했다.','noun','science_en','chemistry'),
('E','bond','결합: 원자나 분자 사이에 작용하는 힘.','Covalent bonds share electrons between atoms.','공유 결합은 원자들 사이에 전자를 공유한다.','noun','science_en','chemistry'),
('E','acid','산: 물에 녹아 수소 이온(H+)을 내놓는 물질.','Lemon juice is acidic because it contains citric acid.','레몬 주스는 시트르산이 포함되어 있어 산성이다.','noun','science_en','chemistry'),
('E','mixture','혼합물: 두 가지 이상의 물질이 화학적으로 결합하지 않고 섞여 있는 상태.','Air is a mixture of gases like nitrogen and oxygen.','공기는 질소와 산소와 같은 기체들의 혼합물이다.','noun','science_en','chemistry'),
('E','ion','이온: 전하를 띤 원자 또는 분자.','A sodium ion (Na+) has lost an electron.','나트륨 이온(Na+)은 전자를 잃었다.','noun','science_en','chemistry'),
('E','periodic table','주기율표: 원소들을 원자 번호 순서대로 배열한 표.','The periodic table organizes elements by their properties.','주기율표는 원소들을 그들의 성질에 따라 분류한다.','noun phrase','science_en','chemistry'),
('E','oxidation','산화: 물질이 전자를 잃는 과정.','Rusting is a type of oxidation.','녹스는 것은 산화의 한 종류이다.','noun','science_en','chemistry'),
('E','catalyst','촉매: 화학 반응의 속도를 변화시키지만 자신은 변하지 않는 물질.','Enzymes act as catalysts in biological reactions.','효소는 생물학적 반응에서 촉매 역할을 한다.','noun','science_en','chemistry'),
('E','valence electron','원자가 전자: 원자의 가장 바깥 껍질에 있는 전자.','Valence electrons determine how an atom will bond.','원자가 전자는 원자가 어떻게 결합할지를 결정한다.','noun phrase','science_en','chemistry'),
('E','chemical formula','화학식: 화합물을 구성하는 원소와 그 수를 나타내는 기호.','The chemical formula for water is H2O.','물의 화학식은 H2O이다.','noun phrase','science_en','chemistry'),
('E','organic chemistry','유기 화학: 탄소를 포함하는 화합물을 연구하는 화학의 한 분야.','Organic chemistry is essential for understanding life.','유기 화학은 생명을 이해하는 데 필수적이다.','noun phrase','science_en','chemistry'),
('E','inorganic chemistry','무기 화학: 탄소를 포함하지 않는 화합물을 연구하는 화학의 한 분야.','Inorganic chemistry deals with minerals and metals.','무기 화학은 광물과 금속을 다룬다.','noun phrase','science_en','chemistry'),
('E','equilibrium','평형: 화학 반응에서 정반응과 역반응의 속도가 같아 더 이상 농도가 변하지 않는 상태.','The reaction reached equilibrium after two hours.','그 반응은 2시간 후에 평형에 도달했다.','noun','science_en','chemistry'),
('E','precipitate','침전물: 용액에서 분리되어 고체로 가라앉는 물질.','A white precipitate formed when the two solutions were mixed.','두 용액을 섞었을 때 흰색 침전물이 형성되었다.','noun','science_en','chemistry'),
('E','solvent','용매: 다른 물질(용질)을 녹이는 액체.','Water is often called the universal solvent.','물은 종종 만능 용매라고 불린다.','noun','science_en','chemistry'),
('E','solute','용질: 용매에 녹는 물질.','In saltwater, salt is the solute.','소금물에서 소금은 용질이다.','noun','science_en','chemistry'),
('E','pH','pH: 용액의 산성 또는 염기성을 나타내는 척도.','The pH scale ranges from 0 to 14.','pH 척도는 0에서 14까지이다.','noun','science_en','chemistry'),
('E','titration','적정: 용액의 농도를 결정하기 위해 알려진 농도의 다른 용액과 반응시키는 분석 방법.','Titration is used to determine the concentration of an unknown acid.','적정은 미지의 산의 농도를 결정하는 데 사용된다.','noun','science_en','chemistry'),
('E','stoichiometry','화학량론: 화학 반응에서 물질들 사이의 정량적 관계를 다루는 분야.','Stoichiometry helps predict the amount of product formed.','화학량론은 생성되는 생성물의 양을 예측하는 데 도움이 된다.','noun','science_en','chemistry'),
('E','isotope','동위 원소: 같은 원소이지만 중성자 수가 다른 원자.','Carbon-14 is an isotope used for dating.','탄소-14는 연대 측정에 사용되는 동위 원소이다.','noun','science_en','chemistry'),
('E','covalent bond','공유 결합: 원자들이 전자를 공유하여 형성되는 화학 결합.','Water molecules are held together by covalent bonds.','물 분자는 공유 결합으로 함께 유지된다.','noun phrase','science_en','chemistry'),
('E','ionic bond','이온 결합: 양이온과 음이온 사이에 작용하는 정전기적 인력에 의해 형성되는 화학 결합.','Sodium chloride is formed by an ionic bond.','염화나트륨은 이온 결합으로 형성된다.','noun phrase','science_en','chemistry'),
('E','metallic bond','금속 결합: 금속 원자들 사이에서 자유롭게 움직이는 전자들에 의해 형성되는 결합.','Metallic bonds explain why metals conduct electricity.','금속 결합은 금속이 전기를 전도하는 이유를 설명한다.','noun phrase','science_en','chemistry'),
('E','polymer','고분자: 반복되는 작은 단위(단량체)로 구성된 큰 분자.','Plastic is a common example of a polymer.','플라스틱은 고분자의 흔한 예이다.','noun','science_en','chemistry'),
('E','monomer','단량체: 고분자를 형성하기 위해 결합할 수 있는 작은 분자.','Glucose is a monomer that forms starch.','포도당은 녹말을 형성하는 단량체이다.','noun','science_en','chemistry'),
('E','combustion','연소: 연료가 산소와 빠르게 반응하여 열과 빛을 생성하는 과정.','The combustion of wood produces ash and smoke.','나무의 연소는 재와 연기를 생성한다.','noun','science_en','chemistry'),
('E','reduction','환원: 물질이 전자를 얻는 과정.','Reduction often occurs with oxidation in a redox reaction.','환원은 산화 환원 반응에서 산화와 함께 자주 발생한다.','noun','science_en','chemistry'),
('E','redox reaction','산화 환원 반응: 산화와 환원이 동시에 일어나는 화학 반응.','Batteries work based on redox reactions.','배터리는 산화 환원 반응을 기반으로 작동한다.','noun phrase','science_en','chemistry'),
('E','Rock','암석','Igneous rocks are formed from molten magma or lava.','화성암은 녹은 마그마나 용암으로부터 형성됩니다.','noun','science_en','earth'),
('E','Mineral','광물','Quartz is a common mineral found in many rocks.','석영은 많은 암석에서 발견되는 흔한 광물입니다.','noun','science_en','earth'),
('E','Plate Tectonics','판 구조론','Plate tectonics explains the movement of Earth''s continents.','판 구조론은 지구 대륙의 이동을 설명합니다.','noun phrase','science_en','earth'),
('E','Magma','마그마','Magma erupts from a volcano as lava.','마그마는 화산에서 용암으로 분출됩니다.','noun','science_en','earth'),
('E','Lava','용암','The hot lava flowed down the mountainside.','뜨거운 용암이 산비탈을 따라 흘러내렸습니다.','noun','science_en','earth'),
('E','Weather','날씨','The weather today is sunny with a gentle breeze.','오늘 날씨는 부드러운 산들바람과 함께 맑습니다.','noun','science_en','earth'),
('E','Erosion','침식','Wind and water cause soil erosion.','바람과 물은 토양 침식을 일으킵니다.','noun','science_en','earth'),
('E','Sedimentary Rock','퇴적암','Sandstone is a common type of sedimentary rock.','사암은 흔한 퇴적암의 한 종류입니다.','noun phrase','science_en','earth'),
('E','Metamorphic Rock','변성암','Marble is a metamorphic rock formed from limestone.','대리석은 석회암에서 형성된 변성암입니다.','noun phrase','science_en','earth'),
('E','Core','핵','The Earth''s core is made of iron and nickel.','지구의 핵은 철과 니켈로 이루어져 있습니다.','noun','science_en','earth'),
('E','Mantle','맨틀','The mantle is the layer above the Earth''s core.','맨틀은 지구 핵 위의 층입니다.','noun','science_en','earth'),
('E','Crust','지각','The Earth''s crust is the outermost solid shell.','지구의 지각은 가장 바깥쪽의 단단한 껍질입니다.','noun','science_en','earth'),
('E','Tectonic Plate','지각판','The Pacific Plate is the largest tectonic plate on Earth.','태평양판은 지구에서 가장 큰 지각판입니다.','noun phrase','science_en','earth'),
('E','Fault Line','단층선','An earthquake occurs along a fault line.','지진은 단층선을 따라 발생합니다.','noun phrase','science_en','earth'),
('E','Tsunami','쓰나미','A powerful earthquake can trigger a tsunami.','강력한 지진은 쓰나미를 일으킬 수 있습니다.','noun','science_en','earth'),
('E','Crater','분화구','The volcano''s crater was filled with ash.','화산의 분화구는 재로 가득 차 있었습니다.','noun','science_en','earth'),
('E','Troposphere','대류권','Most weather phenomena occur in the troposphere.','대부분의 일기 현상은 대류권에서 발생합니다.','noun','science_en','earth'),
('E','Stratosphere','성층권','The ozone layer is found in the stratosphere.','오존층은 성층권에서 발견됩니다.','noun','science_en','earth'),
('E','Humidity','습도','High humidity can make the air feel sticky.','높은 습도는 공기를 끈적하게 느끼게 할 수 있습니다.','noun','science_en','earth'),
('E','Deposition','퇴적','Sediment deposition creates new landforms.','퇴적물 퇴적은 새로운 지형을 만듭니다.','noun','science_en','earth'),
('E','Constellation','별자리','Orion is a well-known constellation in the night sky.','오리온은 밤하늘의 잘 알려진 별자리입니다.','noun','science_en','earth'),
('E','Asteroid','소행성','An asteroid is a rocky body orbiting the Sun.','소행성은 태양을 공전하는 암석질 천체입니다.','noun','science_en','earth'),
('E','Force','힘 (물체의 운동 상태를 변화시키거나 변형시키는 원인)','A net force is required to change an object''s velocity.','물체의 속도를 바꾸려면 알짜힘이 필요하다.','noun','science_en','physics'),
('E','Motion','운동 (물체의 위치 변화)','Newton''s laws of motion describe how objects move.','뉴턴의 운동 법칙은 물체가 어떻게 움직이는지 설명한다.','noun','science_en','physics'),
('E','Acceleration','가속도 (속도의 변화율)','The acceleration due to gravity on Earth is approximately 9.8 m/s².','지구에서 중력 가속도는 약 9.8 m/s²이다.','noun','science_en','physics'),
('E','Potential Energy','위치 에너지 (물체의 위치나 상태에 따라 저장된 에너지)','A ball held high above the ground has potential energy.','땅 위 높이 들고 있는 공은 위치 에너지를 가진다.','noun','science_en','physics'),
('E','Kinetic Energy','운동 에너지 (움직이는 물체가 가지는 에너지)','The faster the object moves, the greater its kinetic energy.','물체가 빠르게 움직일수록 운동 에너지가 커진다.','noun','science_en','physics'),
('E','Momentum','운동량 (물체의 질량과 속도의 곱)','The total momentum of a system remains constant if no external forces act on it.','외부 힘이 작용하지 않으면 계의 총 운동량은 일정하게 유지된다.','noun','science_en','physics'),
('E','Friction','마찰력 (두 표면이 접촉하여 움직일 때 운동을 방해하는 힘)','Friction can generate heat.','마찰력은 열을 발생시킬 수 있다.','noun','science_en','physics'),
('E','Wave','파동 (에너지를 전달하는 진동)','Light and sound travel as waves.','빛과 소리는 파동으로 전달된다.','noun','science_en','physics'),
('E','Amplitude','진폭 (파동의 평형 위치로부터의 최대 변위)','The amplitude of the wave affects its intensity.','파동의 진폭은 그 세기에 영향을 미친다.','noun','science_en','physics'),
('E','Circuit','회로 (전류가 흐를 수 있는 닫힌 경로)','This circuit includes a resistor and a capacitor.','이 회로에는 저항기와 축전기가 포함되어 있다.','noun','science_en','physics'),
('E','Current','전류 (전하의 흐름)','The electric current flows from the positive to the negative terminal.','전류는 양극에서 음극으로 흐른다.','noun','science_en','physics'),
('E','Voltage','전압 (회로의 두 점 사이의 전위차)','A higher voltage can push more current through a circuit.','더 높은 전압은 회로를 통해 더 많은 전류를 밀어낼 수 있다.','noun','science_en','physics'),
('E','Resistance','저항 (전류의 흐름을 방해하는 정도)','Metals generally have low electrical resistance.','금속은 일반적으로 전기 저항이 낮다.','noun','science_en','physics'),
('E','Power','일률 (단위 시간당 전달되거나 변환되는 에너지의 양)','Electrical power is the product of voltage and current.','전력은 전압과 전류의 곱이다.','noun','science_en','physics'),
('E','Work','일 (힘을 가하여 물체를 이동시키는 에너지의 양)','Work is done when a force causes displacement.','힘이 변위를 일으킬 때 일이 수행된다.','noun','science_en','physics'),
('E','Newton''s First Law','뉴턴의 제1법칙 (관성의 법칙)','An object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force.','정지해 있는 물체는 외부 힘이 작용하지 않으면 계속 정지해 있고, 운동하는 물체는 외부 힘이 작용하지 않으면 같은 속도와 방향으로 계속 운동한다.','phrase','science_en','physics'),
('E','Newton''s Second Law','뉴턴의 제2법칙 (가속도의 법칙)','The acceleration of an object is directly proportional to the net force acting upon it and inversely proportional to its mass (F=ma).','물체의 가속도는 물체에 작용하는 알짜힘에 비례하고 질량에 반비례한다 (F=ma).','phrase','science_en','physics'),
('E','Newton''s Third Law','뉴턴의 제3법칙 (작용-반작용의 법칙)','For every action, there is an equal and opposite reaction.','모든 작용에는 크기가 같고 방향이 반대인 반작용이 있다.','phrase','science_en','physics'),
('E','Inertia','관성 (물체가 자신의 운동 상태를 유지하려는 성질)','A passenger in a car often feels inertia when the car suddenly stops.','자동차 안의 승객은 차가 갑자기 멈출 때 종종 관성을 느낀다.','noun','science_en','physics'),
('E','Centripetal Force','구심력 (원운동하는 물체를 원의 중심으로 향하게 하는 힘)','The centripetal force is necessary to keep an object moving in a circle.','물체를 원형으로 계속 움직이게 하려면 구심력이 필요하다.','noun','science_en','physics'),
('E','Centrifugal Force','원심력 (원운동하는 물체가 바깥으로 나가려는 힘 (관성력))','When turning sharply, you can feel a centrifugal force pushing you outwards.','급격하게 회전할 때, 바깥으로 밀어내는 원심력을 느낄 수 있다.','noun','science_en','physics'),
('E','Sound Wave','음파 (소리를 전달하는 파동)','Sound waves travel through the air.','음파는 공기를 통해 전달된다.','noun','science_en','physics'),
('E','Light Wave','빛파동 (빛을 전달하는 전자기파)','Light waves can travel through a vacuum.','빛파동은 진공을 통해 전달될 수 있다.','noun','science_en','physics'),
('E','Electromagnetic Wave','전자기파 (전기장과 자기장의 진동으로 이루어진 파동)','Radio waves are a type of electromagnetic wave.','전파는 전자기파의 한 종류이다.','noun','science_en','physics'),
('E','Ohm''s Law','옴의 법칙 (전압, 전류, 저항 사이의 관계를 나타내는 법칙)','Ohm''s law states that voltage is equal to current multiplied by resistance (V=IR).','옴의 법칙은 전압이 전류에 저항을 곱한 값과 같다고 말한다 (V=IR).','phrase','science_en','physics'),
('E','Conservation of Energy','에너지 보존 법칙 (에너지는 생성되거나 소멸되지 않고 형태만 바뀐다는 법칙)','The law of conservation of energy is a fundamental principle in physics.','에너지 보존 법칙은 물리학의 기본적인 원리이다.','phrase','science_en','physics'),
('E','Conservation of Momentum','운동량 보존 법칙 (외부 힘이 작용하지 않는 계에서 총 운동량은 일정하게 보존된다는 법칙)','In a collision between two objects, the total momentum is conserved.','두 물체 사이의 충돌에서 총 운동량은 보존된다.','phrase','science_en','physics'),
('E','Experiment','실험','We conducted an experiment to test the new fertilizer.','우리는 새 비료를 시험하기 위한 실험을 수행했습니다.','noun','science_en',NULL),
('E','Observation','관찰','Careful observation is key to scientific discovery.','주의 깊은 관찰은 과학적 발견의 열쇠입니다.','noun','science_en',NULL),
('E','Molecule','분자','A water molecule is made of two hydrogen atoms and one oxygen atom.','물 분자는 두 개의 수소 원자와 한 개의 산소 원자로 이루어져 있습니다.','noun','science_en',NULL),
('E','Atom','원자','An atom is the basic unit of a chemical element.','원자는 화학 원소의 기본 단위입니다.','noun','science_en',NULL),
('E','Element','원소','Oxygen is an essential element for life.','산소는 생명에 필수적인 원소입니다.','noun','science_en',NULL),
('E','Compound','화합물','Salt is a chemical compound of sodium and chlorine.','소금은 나트륨과 염소의 화학 화합물입니다.','noun','science_en',NULL),
('E','Cell','세포','The basic unit of all living organisms is the cell.','모든 살아있는 유기체의 기본 단위는 세포입니다.','noun','science_en',NULL),
('E','Organism','유기체','Bacteria are single-celled organisms.','박테리아는 단세포 유기체입니다.','noun','science_en',NULL),
('E','Photosynthesis','광합성','Plants use photosynthesis to convert light energy into chemical energy.','식물은 광합성을 사용하여 빛 에너지를 화학 에너지로 전환합니다.','noun','science_en',NULL),
('E','Gravity','중력','Gravity is the force that pulls objects towards each other.','중력은 물체를 서로 끌어당기는 힘입니다.','noun','science_en',NULL),
('E','Velocity','속도','The velocity of the car increased rapidly.','자동차의 속도가 빠르게 증가했습니다.','noun','science_en',NULL),
('E','Energy','에너지','Renewable energy sources are becoming more popular.','재생 가능 에너지원이 점점 더 인기를 얻고 있습니다.','noun','science_en',NULL),
('E','Ecosystem','생태계','The forest is a complex ecosystem.','숲은 복잡한 생태계입니다.','noun','science_en',NULL),
('E','Evolution','진화','Evolution explains the diversity of life on Earth.','진화는 지구상의 생명체의 다양성을 설명합니다.','noun','science_en',NULL),
('E','Reaction','반응','The chemical reaction produced heat.','화학 반응이 열을 발생시켰습니다.','noun','science_en',NULL),
('E','Mass','질량','The mass of an object does not change with location.','물체의 질량은 위치에 따라 변하지 않습니다.','noun','science_en',NULL),
('E','Density','밀도','The density of ice is less than the density of water.','얼음의 밀도는 물의 밀도보다 낮습니다.','noun','science_en',NULL),
('E','Pressure','압력','High pressure can cause water to boil at a higher temperature.','높은 압력은 물을 더 높은 온도에서 끓게 할 수 있습니다.','noun','science_en',NULL),
('E','Temperature','온도','The temperature dropped significantly overnight.','밤사이 기온이 현저히 떨어졌습니다.','noun','science_en',NULL),
('E','Wavelength','파장','Different colors of light have different wavelengths.','다른 색상의 빛은 다른 파장을 가지고 있습니다.','noun','science_en',NULL),
('E','Frequency','주파수','The frequency of the sound wave was very high.','음파의 주파수가 매우 높았습니다.','noun','science_en',NULL),
('E','Orbit','궤도','The Earth orbits the Sun.','지구는 태양 주위를 공전합니다.','noun','science_en',NULL),
('E','Planet','행성','Mars is known as the Red Planet.','화성은 붉은 행성으로 알려져 있습니다.','noun','science_en',NULL),
('E','Star','별','The Sun is our nearest star.','태양은 우리에게 가장 가까운 별입니다.','noun','science_en',NULL),
('E','Galaxy','은하','Our solar system is in the Milky Way galaxy.','우리 태양계는 우리 은하에 있습니다.','noun','science_en',NULL),
('E','Universe','우주','The universe is vast and mysterious.','우주는 광대하고 신비롭습니다.','noun','science_en',NULL),
('E','Fossil','화석','We found a dinosaur fossil in the rock.','우리는 바위에서 공룡 화석을 발견했습니다.','noun','science_en',NULL),
('E','Sediment','퇴적물','Rivers carry sediment to the ocean.','강은 퇴적물을 바다로 운반합니다.','noun','science_en',NULL),
('E','Volcano','화산','The volcano erupted after many years of dormancy.','화산은 수년간의 휴면기 후에 분출했습니다.','noun','science_en',NULL),
('E','Earthquake','지진','An earthquake can cause widespread destruction.','지진은 광범위한 파괴를 일으킬 수 있습니다.','noun','science_en',NULL),
('E','Atmosphere','대기','The Earth''s atmosphere protects us from harmful radiation.','지구의 대기는 유해한 방사선으로부터 우리를 보호합니다.','noun','science_en',NULL),
('E','Climate','기후','The climate is changing rapidly due to global warming.','지구 온난화로 인해 기후가 빠르게 변하고 있습니다.','noun','science_en',NULL),
('E','Pollution','오염','Air pollution is a serious environmental problem.','대기 오염은 심각한 환경 문제입니다.','noun','science_en',NULL),
('E','Conservation','보존','Wildlife conservation efforts are crucial.','야생 동물 보존 노력은 매우 중요합니다.','noun','science_en',NULL),
('E','Variable','변수','In this experiment, temperature is the independent variable.','이 실험에서 온도는 독립 변수입니다.','noun','science_en',NULL),
('E','Constant','상수','The speed of light in a vacuum is a physical constant.','진공에서의 빛의 속도는 물리적 상수입니다.','noun','science_en',NULL),
('E','Data','데이터','We collected data from the experiment.','우리는 실험에서 데이터를 수집했습니다.','noun','science_en',NULL),
('E','Theory','이론','The theory of relativity changed our understanding of space and time.','상대성 이론은 공간과 시간에 대한 우리의 이해를 바꾸었습니다.','noun','science_en',NULL),
('E','Law','법칙','Newton''s laws of motion are fundamental in physics.','뉴턴의 운동 법칙은 물리학의 기본입니다.','noun','science_en',NULL),
('E','Acid','산','Lemon juice is acidic.','레몬 주스는 산성입니다.','noun','science_en',NULL),
('E','Base','염기','Baking soda is a common base.','베이킹 소다는 흔한 염기입니다.','noun','science_en',NULL),
('E','Solution','용액','Salt dissolves in water to form a solution.','소금은 물에 녹아 용액을 형성합니다.','noun','science_en',NULL),
('E','Mixture','혼합물','Air is a mixture of gases.','공기는 기체의 혼합물입니다.','noun','science_en',NULL),
('E','Catalyst','촉매','A catalyst speeds up a chemical reaction without being consumed.','촉매는 소모되지 않고 화학 반응을 가속시킵니다.','noun','science_en',NULL),
('E','Equilibrium','평형','The reaction reached a state of chemical equilibrium.','반응은 화학적 평형 상태에 도달했습니다.','noun','science_en',NULL),
('E','Phase','상','Water can exist in three phases: solid, liquid, and gas.','물은 고체, 액체, 기체의 세 가지 상으로 존재할 수 있습니다.','noun','science_en',NULL)
on conflict (level, term) do nothing;
